- cmd/federation-controller/main.go
- examples/README.md
- internal/pkg/xds/adss/adss_handler.go
- internal/pkg/xds/adss/grpc_server.go
When MCP server and FDS client were started independently, there could happen the following order of events:
1. MCP server was started.
2. FDS client was started.
3. FDS client received exported services.
4. MCP skipped pushing ServiceEntry resources for the received exported services, because there were no subscribers.
5. Istio connected to MCP.
6. MCP pushed 0 ServiceEntry resources.
In such a case, importing mesh was out of sync. To avoid this issue, we can start FDS client after receiving MCP subscription from istiod. This is still not fully correct, because we should start only 1 FDS client for all MCP subscriptions and just trigger FDS push on new MCP subscriptions, but this could be done in a follow-up PR.
> Subscribe exported services when istiod subscribes MCP

- Makefile
Make processes targets in order of their appearance in the `Makefile` [1] and executed first rule not prefixed with `.`.
The current definition of the "default" target is a `.PHONY` which effectively means that only `build` will be executed, as this is the first matching target.
To ensure both `build` and `test` are invoked the `default` phony target is defined instead, as the first one in the `Makefile`.
[1] https://www.gnu.org/software/make/manual/html_node/How-Make-Works.html
> fix(make): defines default target

- Makefile
Each target which is not representing an actual file should be marked as `.PHONY`.
Otherwise running e.g. `make build` twice would result in subsequent execution being skipped with:
```sh
$ make build
make: 'build' is up to date.
```
which is not desired (coincidently we have both `build` and `test` folders in this project).
This change ensures all fake/phony targets are marked respectively and so they are executed each time.
> fix(make): defines cmd targets as PHONY

- .github/workflows/build.yaml
- Makefile
In order to ensure healthy code base we can automate checks as GitHub actions. This way we can spot defects early and make sure all new changes are not breaking anything.
This change brings a simple job which for each PR or push to main branch will trigger unit tests and binary compilation (default target).
> ci: introduces basic unit test job

- cmd/federation-controller/main.go
- examples/exporting-controller.yaml
- go.mod
- internal/pkg/config/federation_config.go
- internal/pkg/config/mesh_peer.go
- internal/pkg/istio/config_factory.go
- internal/pkg/istio/config_factory_test.go
- internal/pkg/mcp/gateway_generator.go
- internal/pkg/mcp/gateway_generator_test.go
- internal/pkg/mcp/import_handler.go
- internal/pkg/mcp/import_handler_test.go
This change will allow to run the controller as an XDS config source server for Istio or as a standard k8s controller that creates and reconciles Istio resources in the k8s api-server.
> Move creating Istio resources to istio.ConfigFactory

- test/scripts/lib.sh
Currently, we do not support east-west gateways with IPv6 address, and the KinD provisioner script was not checking which subnet it gets from the container config, so the [CI](https://github.com/openshift/release/pull/56927) checks fail due to wrong IP address pool:
```
++ docker inspect kind
++ jq '.[0].IPAM.Config[0].Subnet' -r
+ docker_kind_subnet=fc00:f853:ccd:e793::/64
++ python3 /work/test/scripts/find_smaller_subnets.py --network fc00:f853:ccd:e793::/64 --region west
+ cidr=fc00:f853:ccd:e793:4000::/66
+ echo '
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
name: default-pool
namespace: metallb-system
spec:
addresses:
- fc00:f853:ccd:e793:4000::/66
avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
name: default-l2
namespace: …
```
> Fix finding IPv4 subnets assigned to KinD clusters

- chart/templates/clusterrole.yaml
- chart/templates/deployment.yaml
- cmd/federation-controller/main.go
- internal/pkg/config/federation_config.go
- internal/pkg/istio/config_factory.go
- internal/pkg/kube/destination_rule_reconciler.go
- internal/pkg/kube/gateway_reconciler.go
- internal/pkg/kube/reconciler.go
- internal/pkg/kube/reconciler_manager.go
- internal/pkg/kube/service_entry_reconciler.go
- internal/pkg/kube/virtual_service_reconciler.go
- internal/pkg/kube/workload_entry_reconciler.go
- internal/pkg/mcp/service_entry_generator_test.go
- internal/pkg/mcp/workload_entry_generator_test.go
Closes #50
Current limitations:
1. Resources are not cleaned up when controller stops. We will need to add an ownerReference to resources so kube can garbage collect them.
2. Reconcile is not triggered when a user manually updates a resource managed by federation. (we will need an informer and handler similar to [this](https://github.com/openshift-service-mesh/federation/blob/master/cmd/federation-controller/main.go#L149))
3. Reconcilers GET and LIST resources by querying kube-apiserver. We should have a cached lister [similar to this](https://github.com/openshift-service-mesh/federation/blob/master/cmd/federation-controller/main.go#L149) for Istio resources as an optimisation.
> Introduce k8s config mode

- Makefile
Our build process relies on `docker` client to build and push images. In most cases it is all we need, but we can easily open it up for other container tools to be used instead, for example `podman`.
To make it possible, `CONTAINER_CLI` variable is introduced that can be configured when running the build. Named is aligned with the Istio project.
This can be used in a few different ways during the build process:
```sh
make docker -e CONTAINER_CLI=podman
CONTAINER_CLI=podman make docker
export CONTAINER_CLI=podman && make docker
```
> feat(build): configurable container builder

- internal/pkg/fds/exported_service_generator.go
- internal/pkg/fds/import_handler.go
- internal/pkg/istio/config_factory.go
- internal/pkg/kube/destination_rule_reconciler.go
- internal/pkg/kube/gateway_reconciler.go
- internal/pkg/kube/service_entry_reconciler.go
- internal/pkg/kube/virtual_service_reconciler.go
- internal/pkg/kube/workload_entry_reconciler.go
- internal/pkg/mcp/gateway_generator.go
- internal/pkg/mcp/service_entry_generator.go
- internal/pkg/mcp/workload_entry_generator.go
- internal/pkg/xds/adsc/adsc.go
- test/e2e/common/setup.go
- test/e2e/common/traffic_tests.go
Instead of printing a string representation of an error using `%v`, we can wrap it with `%w`. This makes handling and debugging it easier.
Quick find-replace to wrap errors using `%w` instead of `%v` when using `fmt.Errorf`.
Discussed in #61.
> chore(errors): wraps errors using %w

- Makefile
Executing `make kind-clusters` on a clean environment results with the error:
```sh
+ for cluster_name in "east" "west"
+ kind load docker-image --nodes east-control-plane --name east quay.io/maistra-dev/federation-controller:test
ERROR: image: "quay.io/maistra-dev/federation-controller:test" not present locally
make: *** [Makefile:42: kind-clusters] Error 1
```
as the image tagged with `test` is not built.
This fix ensures that we build the image when `USE_LOCAL_IMAGE` is set to `true` so kind setup can succeed.
> fix(make): ensures test image is built for kind setup

- Makefile
As we have multiple targets defined having an easy overview of what is available without a need of skimming through `Makefile` can help newcomers.
For this purpose `make help` target has been introduced. Invoking it will print selected targets and their respective comments, giving a structured overview of available commands.
```sh
❯ make help
Usage:
make <target>
Build
build                      Builds the project
test                       Runs tests
docker-build               Builds container image
docker-push                Pushes container image to the registry
docker                     Combines build and push targets
Development
kind-clusters              Provisions KinD clusters for local development or testing
build-test-image           Builds test image
Code Gen
proto …
```
> feat(make): introduces help target

- .gitignore
When running snippets from `examples/README.md` folders with generated certs should be ignored to avoid being accidentally added under source control.
This change ensures both `east` and `west` folders are ignored.
> fix(git): ignores demo cert folders

- internal/pkg/kube/reconciler_manager.go
Runs all reconcilers in a single pass, allowing errors to be collected without early termination. It aligns with the "eventual consistency" nature of reconciling but also enables to either set up more in a single run or capture all problems and troubleshoot more efficiently.
By using `errors.Join` we can achieve "multi-error" semantic without using any additional library such as [hashicorp/go-multierror](https://github.com/hashicorp/go-multierror).
> feat(k8s): run all reconcilers in a single pass

- Makefile
Some tools may require adjustments to the build process, such as adding specific `ldflags`. These modifications are not always necessary or suitable for production binaries. Altering them directly in the default build target would not be ideal.
The `Makefile` now supports an `EXTRA_BUILD_ARGS` variable, enabling customization of the build process. For example, if a tool requires a dynamic linker, the build can be now modified as follows:
```sh
CGO_ENABLED=1 make build -e EXTRA_BUILD_ARGS='-ldflags "-linkmode external"'
```
> feat(make): customizable build target

- Makefile
Follow-up to #82, where I missed accidental addition of extra forward slashes. Most likely some rename mishap.
> chore(make): removes excessive // in paths

- internal/pkg/config/federation_config.go
Kubernetes APIs rely on JSON for serialization, making JSON tags more common across the projects.
YAML tags aren't needed since tools like `sigs.k8s.io/yaml` can handle YAML as JSON.
This aligns with the kube-builder approach and practices used in other Kubernetes upstream projects.
> chore: changes yaml to json tags

- .github/workflows/linters.yaml
`make add-license` target is not part of the default Makefile target, therefore it can be overlooked. But even if it were, there's no guarantee it will be run before a PR is opened or updated. 
The `linters/check-license` GitHub job verifies that every relevant file includes
the required license headers. Otherwise, job fails and lists files both in the [logs](https://github.com/bartoszmajsak/ossm-federation/actions/runs/12066829341/job/33648514031?pr=1)
of the job as well as in the [summary](https://github.com/bartoszmajsak/ossm-federation/actions/runs/12066829341?pr=1#summary-33648514031).
> feat(ci): ensures license headers are added

- Makefile
- test/scripts/cluster.sh
- test/scripts/kind_provisioner.sh
- test/scripts/lib.sh
When we want to use a locally built image for testing, instead of relying on the arbitrary `test` tag, we can follow a convention of appending `-local` suffix to any tag configured through the `TAG` variable. Such an appended tag is only used when provisioning KinD clusters and running e2e tests.
This PR simplifies the process of uploading the image to KinD cluster by moving the decision of performing it outside of the function itself. The function now accepts `cluster`, `hub` and `tag` as *ordered* parameters. The last two are defaulted when not passed or passed as empty (`""`).
The scripts have been cleaned up and some functions moved to their own files.
Any function in `lib.sh` and `cluster.sh` can now be invoked directly from the shell. So you can e.g. update image in the running …
> feat(build): simplifies local image upload strategy

- test/scripts/cluster.sh
- test/scripts/kind_provisioner.sh
- test/scripts/lib.sh
This change expands the cluster provisioning logic to support more than two clusters.
Functions for creating clusters and MetalLB are simplified, allowing parameterized invocation from the main script.
Pod and service subnet parameters are removed as they are no longer required. See [this comment](https://github.com/openshift-service-mesh/federation/pull/92#discussion_r1862738653) for details.
Functions are updated to be POSIX-compliant, improving portability across different shells.
Additionally, the `upload_image` function is moved to `cluster.sh` where it belongs.
> chore(kind): simplifies cluster setup

- Makefile
`ci-operator` image used by prow builder does not come with `unzip` tool causing `proto` target to fail.
This change reworks extracting `protoc` binary using python3 snippet instead, which is available as part of prow toolchain. We also rely on it to calculate subnets for `kind` clusters provisioning.
This will fix #95 and #96.
> fix(ci): uses python3 instead of unzip

- Makefile
E2E tests rely on external tools such as `helm`. With the introduction of `tools` target we are able to provide those binaries with the version we need, but running `make e2e` on freshly cloned project can fail, as ensuring that right tools are on the `PATH` is not part of it.
This change adds `tools` as dependent target for `e2e` and makes required binaries part of used `PATH` so test code can invoked needed commands.
> fix(make): ensures tools installation for e2e tests

- Makefile
In order to ensure that up-to-date codebase is used to build the binary, we should automate  Golang stubs generation based on protobuf API changes.
This step was missing in the build process, requiring developer to call it explicitly.
With this fix, `proto` stubs are generated automatically. Additionally license headers are added, otherwise generation makes them disappear. As a bonus we ensure all relevant source files have now license headers added for each invocation of `build` target.
> fix(make): ensures binary is built against up-to-date code

- chart/templates/deployment.yaml
- cmd/federation-controller/main.go
- internal/pkg/config/cluster.go
We do not need special environment variable to determine where our controller runs. To achieve this we could either use Downward API environment variable called `POD_NAMESPACE` or rely on the fact that we are using Service Account which automatically propagates namespace as mounted secret.
This PR introduces `config.Namespace` function which resolves namespace in the exact order mentioned above or falls back to `istio-system`.
Bonus: it also re-uses Istio's underyling k8s client for the informers instead of creating new instance.
> feat(config): controller's namespace autodiscovery

- api/proto/federation/v1alpha1/exported_service.proto
- cmd/federation-controller/main.go
- internal/api/federation/v1alpha1/exported_service.pb.go
- internal/pkg/fds/exported_service_generator_test.go
- internal/pkg/fds/import_handler.go
- internal/pkg/fds/imported_service_store.go
- internal/pkg/istio/config_factory.go
- internal/pkg/xds/adsc/adsc.go
- internal/pkg/xds/adsc/response_handler.go
- internal/pkg/xds/adss/adss_handler.go
> [!IMPORTANT]
> This PR doesn't include the code required to handle multiple peers yet.
> This is a refactoring of existing data structures first and preserves the current logic.
This PR refactors existing code to facilitate more than one peer by keeping
each federated service (imported from remote) grouped by remote's name.
Initial assumption to rely on `XFCC` header was unsuccessful, as received gRPC 
stream did not have expected headers (or I couldn't get them by using gRPC API
for fetching Metadata in case of Aggregated Discover Service).
Instead of relying on the peer identity passed as part of discovery
response we can group federated services by remote names (aliases)
defined as initial config. 
With this approach we can ensure uniqueness of peer names locally
(which will be …
> feat(fds): groups federated services by remote peers

- test/e2e/common/setup.go
If we do not set `--istio.test.tag` when running tests (which can happen from the IDE), Echo App uses `latest` tag, as we do not propogate default `istioVersion` we have defined in the test setup.
As a consequence tests are failing, because `app:latest` is 5y old and does not support flags defined for the container in Istio Test Framework template.
Additionally `istioVersion` variable has been aligned with what's defined as default in the `Makefile`.
> fix(e2e): aligns echo app version with Istio

- Makefile
To avoid misconfigured go imports we can invoke `fix-imports` as part of the `build` target.
This can limit cases when PRs come with wrongly formatted code.
> feat(build): adds fix-imports to build target

- cmd/federation-controller/main.go
We shouldn't wait indefinitely by using `select {}`, but until the main context is `Done`. 
It ensures we exit the process cleanly in case of termination or cancel. This way kubelet can restart the controller instead of keeping it running in a broken state (i.e. reconciller will stop working when context is `Done`).
> fix(cmd): wait for root context to finish

- internal/pkg/config/parse.go
Previously, the configuration parsing used a default JSON decoder that ignored any unknown fields. This could lead to runtime errors when the configuration contained typos or unrecognized properties.
By switching to a decoder that rejects unknown fields, we ensure that configuration errors are caught early.
> fix(config): fails on unknown fields

- test/scripts/find_subnets.py
In the reworked version of subnet calculation script (#99) we removed the additional subnet creation.
This proved to be necessary, as there's an issue when re-using first subnet, leading to flaky setup, especially when using `istioctl`.
The overlap manifests itself with timeng out when calling `kube-apiserver`:
<details>
<summary>$ istioctl connection errors</summary>
```sh
2024-12-16T11:25:04.161607Z	info	tf	istioctl error: Error: check minimum supported Kubernetes version: error getting Kubernetes version: Get "https://127.0.0.1:42735/version?timeout=5s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2024-12-16T11:25:04.161635Z	error	tf	Test setup error: failed to deploy istio: stdout: ; err: check minimum supported Kubernetes version: error getting …
```
> fix(e2e): creates more subnets for kind clusters

- Makefile
Previously, the `Makefile` tracked binaries like `protoc-gen-golang-deepcopy`
based on the `./bin/` directory timestamp. This caused unnecessary downloads
whenever files inside the directory were modified, as directory `mtime` updates
on file creation, modification, or deletion.
This change ensures that directory is always created first and is not
used as prerequisite for other files to be downloaded there, thus avoiding
re-downloading them due to the fact that `mtime` of the directory is always
newer than the last downloaded file.
In both cases `protoc` is updating `mtime` of `bin` and thus making it newer that all the files in this directory.
This triggers remake of all the targets and so downloads of the binaries when the target depend on `$(LOCALBIN)`.
<details>
<summary>$ make …
> fix(make): prevents redundant binary downloads

- Makefile
Aims to make `build` as lean as possible with the only goal to produce
the binary. At the same time moving license and import fixes to chain of
default targets.
Without this change there's always license added after regenerating
protobuf go stubs. When using tools such as air-verse/air to rebuild the
project on code changes this leads to unnecessary build loops, as one
change triggers `make build` process which leads to watch reacting on
licenses added to source files and re-triggering the build.
> [!NOTE]
> This can be obviously solved by simplifying rebuild command in the tool itself by
> swapping it from `make build` to `go build` but I thought we could
> simplify it on the `Makefile` level.
> chore(make): simplifies build target

- Makefile
`go get ./...` is unnecessary with Go modules, can cause unwanted updates, and is only relevant for legacy projects.
This PR introduces new `deps` target that relies on `go mod` commands.
> feat(make): replaces `go get` with `deps` target

- Makefile
One of my previous PRs (#109) introduces nicely hidden bug which
essentially always result in running first suite from the list of
TEST_SUITES.
This change brings back the proper way of wrapping `foreach` in an eval
clause.
> fix(make): runs all e2e suites

- Makefile
`protoc`, while regenerating the go files is removing the license header
and changes imports order.
With this change we add the license back and fix imports after regenerating
protobuf sources, so it's always consistent.
> chore(make): ensures protoc generated code is correctly formatted

- internal/pkg/xds/adsc/adsc.go
When import rules will change, we have to request SotW from other peers to
reconfigure local mesh.
This PR simply unexports Send method of FDS client so it can be called
by owning controller.
> feat(fds-client): enables sending discovery requests

- cmd/federation-controller/main.go
- internal/pkg/xds/adsc/adsc.go
- internal/pkg/xds/adss/adss_handler.go
- internal/pkg/xds/adss/grpc_server.go
My understanding of the current client-server flow is as follows:
- client connects to the server
- it requests push of predefined types (ExportedSvc) as initial push
request - SotW
- on subscriber(client) connect, server does another SotW push
Not only we are sending the same data twice, but we also need to make
sure that handlers we define are aligned with initial push requests.
If we add new handler, we need to explictly define it as part of
initial push. It also needs to be defined (again) in onSubscribe
on the FDS server side.
This PR moves the initial sync responsibility to the client, ensuring
each handler automatically requests the data it needs. This avoids
redundant pushes and reduces code duplication.
> fix(fds): simplifies sync logic

- cmd/federation-controller/main.go
- internal/pkg/xds/adsc/adsc.go
FDS Client keeps remote mesh name which was confusingly named PeerName.
This PR changes this name so we stick to the same terminology as in
upcoming CRDs.
The `config.meshPeers` is going away so it wasn't reworked, as that would
require splitting struct to local/remotes.
> chore(fds): renames peer to remote

- cmd/federation-controller/main.go
- internal/pkg/xds/adsc/adsc.go
Adhering to [golang conventions](https://go.dev/wiki/Errors#naming) will make the code easier to read for everyone and simplify snowballing when we introduce linters.
This PR renames every error variable that users `err` as suffix to be its prefix instead.
> chore: renames err vars to follow conventions

- Makefile
- cmd/federation-controller/main.go
- internal/controller/meshfederation_controller.go
- internal/pkg/config/parse.go
- internal/pkg/fds/imported_service_store.go
- test/e2e/scenarios/remote_dns_name/main_test.go
- test/e2e/scenarios/remote_ip/main_test.go
- test/e2e/scenarios/spire/main_test.go
- test/e2e/scenarios/spire/setup.go
- test/e2e/setup/cluster_cmds.go
- test/e2e/setup/coredns/patch.go
- test/e2e/setup/federation.go
- test/e2e/traffic_tests.go
While working on #159 my IDE moved local imports around
and `goimports` didn't reformat it properly. It would be good to have
clear rules for grouping and separating libraries we rely on that are
applied deterministically. It seems that `goimports` is fairly limited
and can handle only sorting and basic grouping. This can lead to noise
in PRs which we shouldn't bother about.
This PR changes `fix-imports` target to use `gci` tool instead. This
tool offers more granular control over group definitions so we can
ensure consistency across the codebase.
> [!NOTE]
> Even though `gci` is part of `golangci-lint` I deliberately added it
> as a standalone tool. Introducing the latter is a bigger task which I
> hope I can soon contribute.
> feat(build): replaces goimports with gci

- cmd/federation-controller/main.go
- internal/controller/federatedservice/federatedservice_controller.go
- internal/controller/meshfederation/meshfederation_controller.go
Constructor function ensures that each controller instance
is created with all required objects.
This PR introduces these functions to existing controllers and move each
of controllers to their own packages. This way we can keep all related
logic in a single, dedicated place instead  mixing them in a single pkg
`controller`. It also simplifies the approach of using constructor
functions. Now we can call `meshfederation.NewReconciler` or
`federatedservice.NewReconciler` accordingly.
> feat(ctlr): introduces constructor function

- Makefile
- Makefile.tooling.mk
As our build chain is growing it might be helpful to split Makefile to
several dedicated files which we can compose in the main `Makefile`.
This will help with identifying revelant targets quicker and group
together certain aspects of build process for easier maintenance.
This PR introduces `Makefile.tooling.mk`, where all targets for fetching
tools are now located.
- `make help` has a correct pattern matching and shows targets that
contain numbers in them (i.e. `e2e`)
- test targets are grouped together
- `OUT_DIR` is prepended with `PROJECT_DIR`
> chore(build): reorganizes Makefile

- PROJECT
- api/v1alpha1/federatedservice_types.go
- api/v1alpha1/meshfederation_types.go
- chart/crds/federation.openshift-service-mesh.io_meshfederations.yaml
Current assumption is that we have all our resources namespaced.
This PR changes the scope of existing resources to be namespaced.
> fix(api): changes scope of CRs to Namespaced

- internal/controller/finalizer/types.go
- internal/controller/retry.go
We are going to leverage finalizers to ensure we properly release
any resources owned by our controllers. That includes resources we
cannot garbage collect using `ownerRef` but also things like gRPC
connections we are going to establish between meshes.
Providing consistent approach to deal with this scenario helps us write cleaner and
maintainable code.
This change brings `finalizer` package to address this.
It has `finalizer.Handler` struct that:
- adds finalizer to a given object if it does not exists and then persist it
- performs cleanup defined as `CleanupFn` if the object is marked for deletion
Example usage in the controller reconcile loop:
```golang
finalizerHandler := finalizer.NewHandler(r.Client, "federation.openshift-service-mesh.io/mesh-federation")
if finalized, errFinalize …
```
> feat(ctrl): encapsulates finalizer logic in reusable pkg

- internal/controller/meshfederation/meshfederation_controller.go
- internal/controller/predicate.go
`finalizer.Handler` introduced in #164 is expected to retrigger
reconcile when finalizer is added for the first time. This ensures that
given controller adds its cleanup hook to the resource as soon as
possible.
However adding finalizer does not increase generation of the resource,
therefore using `WithEventFilter(predicate.GenerationChangedPredicate{})`
will not cause another reconcile.
This PR brings `FinalizerChanged` predicate which can be combined:
```golang
WithEventFilter(
predicate.Or(
predicate.GenerationChangedPredicate{},
FinalizerChanged(),
),
).
```
and it will trigger reconciliation on the finalizer change.
> feat(ctrl): predicate on finalizer change

- DEVELOPER.md
- Makefile
`DEVELOPER.md` has been updated to reflect latest tool chain and
simplifications made over the time.
This PR is a follow-up to #106.
> docs: updates dev guide
